[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile.multi-stage"

[deploy]
startCommand = "node server.js"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
healthcheckPath = "/api/health"
healthcheckTimeout = 300